name: Release to GitHub Package Registry

on: push

jobs:
  build-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: mvn clean install
